// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "link.hxx"

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace link
          {
            // linkType
            // 

            const linkType::cost_optional& linkType::
            cost () const
            {
              return this->cost_;
            }

            linkType::cost_optional& linkType::
            cost ()
            {
              return this->cost_;
            }

            void linkType::
            cost (const cost_type& x)
            {
              this->cost_.set (x);
            }

            void linkType::
            cost (const cost_optional& x)
            {
              this->cost_ = x;
            }

            const linkType::bandwidth_optional& linkType::
            bandwidth () const
            {
              return this->bandwidth_;
            }

            linkType::bandwidth_optional& linkType::
            bandwidth ()
            {
              return this->bandwidth_;
            }

            void linkType::
            bandwidth (const bandwidth_type& x)
            {
              this->bandwidth_.set (x);
            }

            void linkType::
            bandwidth (const bandwidth_optional& x)
            {
              this->bandwidth_ = x;
            }

            const linkType::firstNode_type& linkType::
            firstNode () const
            {
              return this->firstNode_.get ();
            }

            linkType::firstNode_type& linkType::
            firstNode ()
            {
              return this->firstNode_.get ();
            }

            void linkType::
            firstNode (const firstNode_type& x)
            {
              this->firstNode_.set (x);
            }

            void linkType::
            firstNode (::std::auto_ptr< firstNode_type > x)
            {
              this->firstNode_.set (x);
            }

            const linkType::secondNode_type& linkType::
            secondNode () const
            {
              return this->secondNode_.get ();
            }

            linkType::secondNode_type& linkType::
            secondNode ()
            {
              return this->secondNode_.get ();
            }

            void linkType::
            secondNode (const secondNode_type& x)
            {
              this->secondNode_.set (x);
            }

            void linkType::
            secondNode (::std::auto_ptr< secondNode_type > x)
            {
              this->secondNode_.set (x);
            }

            const linkType::topologyParameter_sequence& linkType::
            topologyParameter () const
            {
              return this->topologyParameter_;
            }

            linkType::topologyParameter_sequence& linkType::
            topologyParameter ()
            {
              return this->topologyParameter_;
            }

            void linkType::
            topologyParameter (const topologyParameter_sequence& s)
            {
              this->topologyParameter_ = s;
            }

            const linkType::id_type& linkType::
            id () const
            {
              return this->id_.get ();
            }

            linkType::id_type& linkType::
            id ()
            {
              return this->id_.get ();
            }

            void linkType::
            id (const id_type& x)
            {
              this->id_.set (x);
            }

            void linkType::
            id (::std::auto_ptr< id_type > x)
            {
              this->id_.set (x);
            }


            // topologyParameterType
            // 

            const topologyParameterType::topology_type& topologyParameterType::
            topology () const
            {
              return this->topology_.get ();
            }

            topologyParameterType::topology_type& topologyParameterType::
            topology ()
            {
              return this->topology_.get ();
            }

            void topologyParameterType::
            topology (const topology_type& x)
            {
              this->topology_.set (x);
            }

            void topologyParameterType::
            topology (::std::auto_ptr< topology_type > x)
            {
              this->topology_.set (x);
            }

            const topologyParameterType::type_type& topologyParameterType::
            type () const
            {
              return this->type_.get ();
            }

            topologyParameterType::type_type& topologyParameterType::
            type ()
            {
              return this->type_.get ();
            }

            void topologyParameterType::
            type (const type_type& x)
            {
              this->type_.set (x);
            }

            void topologyParameterType::
            type (::std::auto_ptr< type_type > x)
            {
              this->type_.set (x);
            }

            const topologyParameterType::value_optional& topologyParameterType::
            value () const
            {
              return this->value_;
            }

            topologyParameterType::value_optional& topologyParameterType::
            value ()
            {
              return this->value_;
            }

            void topologyParameterType::
            value (const value_type& x)
            {
              this->value_.set (x);
            }

            void topologyParameterType::
            value (const value_optional& x)
            {
              this->value_ = x;
            }

            void topologyParameterType::
            value (::std::auto_ptr< value_type > x)
            {
              this->value_.set (x);
            }
          }
        }
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace link
          {
            // linkType
            //

            linkType::
            linkType (const firstNode_type& firstNode,
                      const secondNode_type& secondNode,
                      const id_type& id)
            : ::xml_schema::type (),
              cost_ (::xml_schema::flags (), this),
              bandwidth_ (::xml_schema::flags (), this),
              firstNode_ (firstNode, ::xml_schema::flags (), this),
              secondNode_ (secondNode, ::xml_schema::flags (), this),
              topologyParameter_ (::xml_schema::flags (), this),
              id_ (id, ::xml_schema::flags (), this)
            {
            }

            linkType::
            linkType (const linkType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              cost_ (x.cost_, f, this),
              bandwidth_ (x.bandwidth_, f, this),
              firstNode_ (x.firstNode_, f, this),
              secondNode_ (x.secondNode_, f, this),
              topologyParameter_ (x.topologyParameter_, f, this),
              id_ (x.id_, f, this)
            {
            }

            linkType::
            linkType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              cost_ (f, this),
              bandwidth_ (f, this),
              firstNode_ (f, this),
              secondNode_ (f, this),
              topologyParameter_ (f, this),
              id_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
                this->parse (p, f);
              }
            }

            void linkType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              for (; p.more_elements (); p.next_element ())
              {
                const ::xercesc::DOMElement& i (p.cur_element ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                // cost
                //
                if (n.name () == "cost" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
                {
                  if (!this->cost_)
                  {
                    this->cost_.set (cost_traits::create (i, f, this));
                    continue;
                  }
                }

                // bandwidth
                //
                if (n.name () == "bandwidth" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
                {
                  if (!this->bandwidth_)
                  {
                    this->bandwidth_.set (bandwidth_traits::create (i, f, this));
                    continue;
                  }
                }

                // firstNode
                //
                if (n.name () == "firstNode" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
                {
                  ::std::auto_ptr< firstNode_type > r (
                    firstNode_traits::create (i, f, this));

                  if (!firstNode_.present ())
                  {
                    this->firstNode_.set (r);
                    continue;
                  }
                }

                // secondNode
                //
                if (n.name () == "secondNode" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
                {
                  ::std::auto_ptr< secondNode_type > r (
                    secondNode_traits::create (i, f, this));

                  if (!secondNode_.present ())
                  {
                    this->secondNode_.set (r);
                    continue;
                  }
                }

                // topologyParameter
                //
                if (n.name () == "topologyParameter" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
                {
                  ::std::auto_ptr< topologyParameter_type > r (
                    topologyParameter_traits::create (i, f, this));

                  this->topologyParameter_.push_back (r);
                  continue;
                }

                break;
              }

              if (!firstNode_.present ())
              {
                throw ::xsd::cxx::tree::expected_element< char > (
                  "firstNode",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link");
              }

              if (!secondNode_.present ())
              {
                throw ::xsd::cxx::tree::expected_element< char > (
                  "secondNode",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link");
              }

              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "id" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< id_type > r (
                    id_traits::create (i, f, this));

                  this->id_.set (r);
                  continue;
                }
              }

              if (!id_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "id",
                  "");
              }
            }

            linkType* linkType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class linkType (*this, f, c);
            }

            linkType::
            ~linkType ()
            {
            }

            // topologyParameterType
            //

            topologyParameterType::
            topologyParameterType (const topology_type& topology,
                                   const type_type& type)
            : ::xml_schema::type (),
              topology_ (topology, ::xml_schema::flags (), this),
              type_ (type, ::xml_schema::flags (), this),
              value_ (::xml_schema::flags (), this)
            {
            }

            topologyParameterType::
            topologyParameterType (const topologyParameterType& x,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              topology_ (x.topology_, f, this),
              type_ (x.type_, f, this),
              value_ (x.value_, f, this)
            {
            }

            topologyParameterType::
            topologyParameterType (const ::xercesc::DOMElement& e,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              topology_ (f, this),
              type_ (f, this),
              value_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
                this->parse (p, f);
              }
            }

            void topologyParameterType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "topology" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< topology_type > r (
                    topology_traits::create (i, f, this));

                  this->topology_.set (r);
                  continue;
                }

                if (n.name () == "type" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< type_type > r (
                    type_traits::create (i, f, this));

                  this->type_.set (r);
                  continue;
                }

                if (n.name () == "value" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< value_type > r (
                    value_traits::create (i, f, this));

                  this->value_.set (r);
                  continue;
                }
              }

              if (!topology_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "topology",
                  "");
              }

              if (!type_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "type",
                  "");
              }
            }

            topologyParameterType* topologyParameterType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class topologyParameterType (*this, f, c);
            }

            topologyParameterType::
            ~topologyParameterType ()
            {
            }
          }
        }
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace link
          {
            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (const ::std::string& u,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::tree::error_handler< char > h;

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (const ::std::string& u,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (const ::std::string& u,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  const ::std::string& sid,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  const ::std::string& sid,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::std::istream& is,
                  const ::std::string& sid,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::link::link (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::xercesc::InputSource& i,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::tree::error_handler< char > h;

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::xercesc::InputSource& i,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::xercesc::InputSource& i,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                ::research::noc::application_mapping::unified_framework::schema::link::link (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (const ::xercesc::DOMDocument& d,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              if (f & ::xml_schema::flags::keep_dom)
              {
                ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
                  static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                  ::research::noc::application_mapping::unified_framework::schema::link::link (
                    c, f | ::xml_schema::flags::own_dom, p));

                return r;
              }

              const ::xercesc::DOMElement& e (*d.getDocumentElement ());
              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (n.name () == "link" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
              {
                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                  ::xsd::cxx::tree::traits< ::research::noc::application_mapping::unified_framework::schema::link::linkType, char >::create (
                    e, f, 0));
                return r;
              }

              throw ::xsd::cxx::tree::unexpected_element < char > (
                n.name (),
                n.namespace_ (),
                "link",
                "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link");
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType >
            link (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties&)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
                ((f & ::xml_schema::flags::keep_dom) &&
                 !(f & ::xml_schema::flags::own_dom))
                ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
                : 0);

              ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
              const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (f & ::xml_schema::flags::keep_dom)
                doc.setUserData (::xml_schema::dom::tree_node_key,
                                 (c.get () ? &c : &d),
                                 0);

              if (n.name () == "link" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
              {
                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::link::linkType > r (
                  ::xsd::cxx::tree::traits< ::research::noc::application_mapping::unified_framework::schema::link::linkType, char >::create (
                    e, f, 0));
                return r;
              }

              throw ::xsd::cxx::tree::unexpected_element < char > (
                n.name (),
                n.namespace_ (),
                "link",
                "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link");
            }
          }
        }
      }
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace link
          {
            void
            link (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));

              ::xsd::cxx::tree::error_handler< char > h;

              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
              }
            }

            void
            link (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  ::xml_schema::error_handler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));
              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            link (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));
              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            link (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));

              ::xsd::cxx::tree::error_handler< char > h;

              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
              }
            }

            void
            link (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  ::xml_schema::error_handler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            link (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::link::link (s, m, f));
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            link (::xercesc::DOMDocument& d,
                  const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  ::xml_schema::flags)
            {
              ::xercesc::DOMElement& e (*d.getDocumentElement ());
              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (n.name () == "link" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link")
              {
                e << s;
              }
              else
              {
                throw ::xsd::cxx::tree::unexpected_element < char > (
                  n.name (),
                  n.namespace_ (),
                  "link",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link");
              }
            }

            ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
            link (const ::research::noc::application_mapping::unified_framework::schema::link::linkType& s,
                  const ::xml_schema::namespace_infomap& m,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::serialize< char > (
                  "link",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                  m, f));

              ::research::noc::application_mapping::unified_framework::schema::link::link (*d, s, f);
              return d;
            }

            void
            operator<< (::xercesc::DOMElement& e, const linkType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // cost
              //
              if (i.cost ())
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "cost",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                    e));

                s << ::xml_schema::as_double(*i.cost ());
              }

              // bandwidth
              //
              if (i.bandwidth ())
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "bandwidth",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                    e));

                s << ::xml_schema::as_double(*i.bandwidth ());
              }

              // firstNode
              //
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "firstNode",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                    e));

                s << i.firstNode ();
              }

              // secondNode
              //
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "secondNode",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                    e));

                s << i.secondNode ();
              }

              // topologyParameter
              //
              for (linkType::topologyParameter_const_iterator
                   b (i.topologyParameter ().begin ()), n (i.topologyParameter ().end ());
                   b != n; ++b)
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "topologyParameter",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/link",
                    e));

                s << *b;
              }

              // id
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "id",
                    e));

                a << i.id ();
              }
            }

            void
            operator<< (::xercesc::DOMElement& e, const topologyParameterType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // topology
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "topology",
                    e));

                a << i.topology ();
              }

              // type
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "type",
                    e));

                a << i.type ();
              }

              // value
              //
              if (i.value ())
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "value",
                    e));

                a << *i.value ();
              }
            }
          }
        }
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

