// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "node.hxx"

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace node
          {
            // nodeType
            // 

            const nodeType::cost_optional& nodeType::
            cost () const
            {
              return this->cost_;
            }

            nodeType::cost_optional& nodeType::
            cost ()
            {
              return this->cost_;
            }

            void nodeType::
            cost (const cost_type& x)
            {
              this->cost_.set (x);
            }

            void nodeType::
            cost (const cost_optional& x)
            {
              this->cost_ = x;
            }

            const nodeType::topologyParameter_sequence& nodeType::
            topologyParameter () const
            {
              return this->topologyParameter_;
            }

            nodeType::topologyParameter_sequence& nodeType::
            topologyParameter ()
            {
              return this->topologyParameter_;
            }

            void nodeType::
            topologyParameter (const topologyParameter_sequence& s)
            {
              this->topologyParameter_ = s;
            }

            const nodeType::link_sequence& nodeType::
            link () const
            {
              return this->link_;
            }

            nodeType::link_sequence& nodeType::
            link ()
            {
              return this->link_;
            }

            void nodeType::
            link (const link_sequence& s)
            {
              this->link_ = s;
            }

            const nodeType::routingTableEntry_sequence& nodeType::
            routingTableEntry () const
            {
              return this->routingTableEntry_;
            }

            nodeType::routingTableEntry_sequence& nodeType::
            routingTableEntry ()
            {
              return this->routingTableEntry_;
            }

            void nodeType::
            routingTableEntry (const routingTableEntry_sequence& s)
            {
              this->routingTableEntry_ = s;
            }

            const nodeType::id_type& nodeType::
            id () const
            {
              return this->id_.get ();
            }

            nodeType::id_type& nodeType::
            id ()
            {
              return this->id_.get ();
            }

            void nodeType::
            id (const id_type& x)
            {
              this->id_.set (x);
            }

            void nodeType::
            id (::std::auto_ptr< id_type > x)
            {
              this->id_.set (x);
            }

            const nodeType::core_optional& nodeType::
            core () const
            {
              return this->core_;
            }

            nodeType::core_optional& nodeType::
            core ()
            {
              return this->core_;
            }

            void nodeType::
            core (const core_type& x)
            {
              this->core_.set (x);
            }

            void nodeType::
            core (const core_optional& x)
            {
              this->core_ = x;
            }

            void nodeType::
            core (::std::auto_ptr< core_type > x)
            {
              this->core_.set (x);
            }


            // topologyParameterType
            // 

            const topologyParameterType::topology_type& topologyParameterType::
            topology () const
            {
              return this->topology_.get ();
            }

            topologyParameterType::topology_type& topologyParameterType::
            topology ()
            {
              return this->topology_.get ();
            }

            void topologyParameterType::
            topology (const topology_type& x)
            {
              this->topology_.set (x);
            }

            void topologyParameterType::
            topology (::std::auto_ptr< topology_type > x)
            {
              this->topology_.set (x);
            }

            const topologyParameterType::type_optional& topologyParameterType::
            type () const
            {
              return this->type_;
            }

            topologyParameterType::type_optional& topologyParameterType::
            type ()
            {
              return this->type_;
            }

            void topologyParameterType::
            type (const type_type& x)
            {
              this->type_.set (x);
            }

            void topologyParameterType::
            type (const type_optional& x)
            {
              this->type_ = x;
            }

            void topologyParameterType::
            type (::std::auto_ptr< type_type > x)
            {
              this->type_.set (x);
            }

            const topologyParameterType::value_optional& topologyParameterType::
            value () const
            {
              return this->value_;
            }

            topologyParameterType::value_optional& topologyParameterType::
            value ()
            {
              return this->value_;
            }

            void topologyParameterType::
            value (const value_type& x)
            {
              this->value_.set (x);
            }

            void topologyParameterType::
            value (const value_optional& x)
            {
              this->value_ = x;
            }

            void topologyParameterType::
            value (::std::auto_ptr< value_type > x)
            {
              this->value_.set (x);
            }


            // linkType
            // 

            const linkType::type_type& linkType::
            type () const
            {
              return this->type_.get ();
            }

            linkType::type_type& linkType::
            type ()
            {
              return this->type_.get ();
            }

            void linkType::
            type (const type_type& x)
            {
              this->type_.set (x);
            }

            void linkType::
            type (::std::auto_ptr< type_type > x)
            {
              this->type_.set (x);
            }

            const linkType::value_optional& linkType::
            value () const
            {
              return this->value_;
            }

            linkType::value_optional& linkType::
            value ()
            {
              return this->value_;
            }

            void linkType::
            value (const value_type& x)
            {
              this->value_.set (x);
            }

            void linkType::
            value (const value_optional& x)
            {
              this->value_ = x;
            }

            void linkType::
            value (::std::auto_ptr< value_type > x)
            {
              this->value_.set (x);
            }


            // typeType
            // 


            // routingTableEntryType
            // 

            const routingTableEntryType::source_type& routingTableEntryType::
            source () const
            {
              return this->source_.get ();
            }

            routingTableEntryType::source_type& routingTableEntryType::
            source ()
            {
              return this->source_.get ();
            }

            void routingTableEntryType::
            source (const source_type& x)
            {
              this->source_.set (x);
            }

            void routingTableEntryType::
            source (::std::auto_ptr< source_type > x)
            {
              this->source_.set (x);
            }

            const routingTableEntryType::destination_type& routingTableEntryType::
            destination () const
            {
              return this->destination_.get ();
            }

            routingTableEntryType::destination_type& routingTableEntryType::
            destination ()
            {
              return this->destination_.get ();
            }

            void routingTableEntryType::
            destination (const destination_type& x)
            {
              this->destination_.set (x);
            }

            void routingTableEntryType::
            destination (::std::auto_ptr< destination_type > x)
            {
              this->destination_.set (x);
            }

            const routingTableEntryType::link_type& routingTableEntryType::
            link () const
            {
              return this->link_.get ();
            }

            routingTableEntryType::link_type& routingTableEntryType::
            link ()
            {
              return this->link_.get ();
            }

            void routingTableEntryType::
            link (const link_type& x)
            {
              this->link_.set (x);
            }

            void routingTableEntryType::
            link (::std::auto_ptr< link_type > x)
            {
              this->link_.set (x);
            }


            // type
            // 

            type::
            type (value v)
            : ::xml_schema::string (_xsd_type_literals_[v])
            {
            }

            type::
            type (const char* v)
            : ::xml_schema::string (v)
            {
            }

            type::
            type (const ::std::string& v)
            : ::xml_schema::string (v)
            {
            }

            type::
            type (const ::xml_schema::string& v)
            : ::xml_schema::string (v)
            {
            }

            type::
            type (const type& v,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
            : ::xml_schema::string (v, f, c)
            {
            }

            type& type::
            operator= (value v)
            {
              static_cast< ::xml_schema::string& > (*this) = 
              ::xml_schema::string (_xsd_type_literals_[v]);

              return *this;
            }
          }
        }
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace node
          {
            // nodeType
            //

            nodeType::
            nodeType (const id_type& id)
            : ::xml_schema::type (),
              cost_ (::xml_schema::flags (), this),
              topologyParameter_ (::xml_schema::flags (), this),
              link_ (::xml_schema::flags (), this),
              routingTableEntry_ (::xml_schema::flags (), this),
              id_ (id, ::xml_schema::flags (), this),
              core_ (::xml_schema::flags (), this)
            {
            }

            nodeType::
            nodeType (const nodeType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              cost_ (x.cost_, f, this),
              topologyParameter_ (x.topologyParameter_, f, this),
              link_ (x.link_, f, this),
              routingTableEntry_ (x.routingTableEntry_, f, this),
              id_ (x.id_, f, this),
              core_ (x.core_, f, this)
            {
            }

            nodeType::
            nodeType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              cost_ (f, this),
              topologyParameter_ (f, this),
              link_ (f, this),
              routingTableEntry_ (f, this),
              id_ (f, this),
              core_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
                this->parse (p, f);
              }
            }

            void nodeType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              for (; p.more_elements (); p.next_element ())
              {
                const ::xercesc::DOMElement& i (p.cur_element ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                // cost
                //
                if (n.name () == "cost" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
                {
                  if (!this->cost_)
                  {
                    this->cost_.set (cost_traits::create (i, f, this));
                    continue;
                  }
                }

                // topologyParameter
                //
                if (n.name () == "topologyParameter" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
                {
                  ::std::auto_ptr< topologyParameter_type > r (
                    topologyParameter_traits::create (i, f, this));

                  this->topologyParameter_.push_back (r);
                  continue;
                }

                // link
                //
                if (n.name () == "link" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
                {
                  ::std::auto_ptr< link_type > r (
                    link_traits::create (i, f, this));

                  this->link_.push_back (r);
                  continue;
                }

                // routingTableEntry
                //
                if (n.name () == "routingTableEntry" && n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
                {
                  ::std::auto_ptr< routingTableEntry_type > r (
                    routingTableEntry_traits::create (i, f, this));

                  this->routingTableEntry_.push_back (r);
                  continue;
                }

                break;
              }

              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "id" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< id_type > r (
                    id_traits::create (i, f, this));

                  this->id_.set (r);
                  continue;
                }

                if (n.name () == "core" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< core_type > r (
                    core_traits::create (i, f, this));

                  this->core_.set (r);
                  continue;
                }
              }

              if (!id_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "id",
                  "");
              }
            }

            nodeType* nodeType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class nodeType (*this, f, c);
            }

            nodeType::
            ~nodeType ()
            {
            }

            // topologyParameterType
            //

            topologyParameterType::
            topologyParameterType (const topology_type& topology)
            : ::xml_schema::type (),
              topology_ (topology, ::xml_schema::flags (), this),
              type_ (::xml_schema::flags (), this),
              value_ (::xml_schema::flags (), this)
            {
            }

            topologyParameterType::
            topologyParameterType (const topologyParameterType& x,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              topology_ (x.topology_, f, this),
              type_ (x.type_, f, this),
              value_ (x.value_, f, this)
            {
            }

            topologyParameterType::
            topologyParameterType (const ::xercesc::DOMElement& e,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              topology_ (f, this),
              type_ (f, this),
              value_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
                this->parse (p, f);
              }
            }

            void topologyParameterType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "topology" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< topology_type > r (
                    topology_traits::create (i, f, this));

                  this->topology_.set (r);
                  continue;
                }

                if (n.name () == "type" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< type_type > r (
                    type_traits::create (i, f, this));

                  this->type_.set (r);
                  continue;
                }

                if (n.name () == "value" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< value_type > r (
                    value_traits::create (i, f, this));

                  this->value_.set (r);
                  continue;
                }
              }

              if (!topology_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "topology",
                  "");
              }
            }

            topologyParameterType* topologyParameterType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class topologyParameterType (*this, f, c);
            }

            topologyParameterType::
            ~topologyParameterType ()
            {
            }

            // linkType
            //

            linkType::
            linkType (const type_type& type)
            : ::xml_schema::type (),
              type_ (type, ::xml_schema::flags (), this),
              value_ (::xml_schema::flags (), this)
            {
            }

            linkType::
            linkType (const linkType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              type_ (x.type_, f, this),
              value_ (x.value_, f, this)
            {
            }

            linkType::
            linkType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              type_ (f, this),
              value_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
                this->parse (p, f);
              }
            }

            void linkType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "type" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< type_type > r (
                    type_traits::create (i, f, this));

                  this->type_.set (r);
                  continue;
                }

                if (n.name () == "value" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< value_type > r (
                    value_traits::create (i, f, this));

                  this->value_.set (r);
                  continue;
                }
              }

              if (!type_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "type",
                  "");
              }
            }

            linkType* linkType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class linkType (*this, f, c);
            }

            linkType::
            ~linkType ()
            {
            }

            // typeType
            //

            typeType::
            typeType ()
            : ::xml_schema::string ()
            {
            }

            typeType::
            typeType (const char* _xsd_string_base)
            : ::xml_schema::string (_xsd_string_base)
            {
            }

            typeType::
            typeType (const ::std::string& _xsd_string_base)
            : ::xml_schema::string (_xsd_string_base)
            {
            }

            typeType::
            typeType (const ::xml_schema::string& _xsd_string_base)
            : ::xml_schema::string (_xsd_string_base)
            {
            }

            typeType::
            typeType (const typeType& x,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::string (x, f, c)
            {
            }

            typeType::
            typeType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::string (e, f, c)
            {
            }

            typeType::
            typeType (const ::xercesc::DOMAttr& a,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::string (a, f, c)
            {
            }

            typeType::
            typeType (const ::std::string& s,
                      const ::xercesc::DOMElement* e,
                      ::xml_schema::flags f,
                      ::xml_schema::container* c)
            : ::xml_schema::string (s, e, f, c)
            {
            }

            typeType* typeType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class typeType (*this, f, c);
            }

            typeType::
            ~typeType ()
            {
            }

            // routingTableEntryType
            //

            routingTableEntryType::
            routingTableEntryType (const source_type& source,
                                   const destination_type& destination,
                                   const link_type& link)
            : ::xml_schema::type (),
              source_ (source, ::xml_schema::flags (), this),
              destination_ (destination, ::xml_schema::flags (), this),
              link_ (link, ::xml_schema::flags (), this)
            {
            }

            routingTableEntryType::
            routingTableEntryType (const routingTableEntryType& x,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (x, f, c),
              source_ (x.source_, f, this),
              destination_ (x.destination_, f, this),
              link_ (x.link_, f, this)
            {
            }

            routingTableEntryType::
            routingTableEntryType (const ::xercesc::DOMElement& e,
                                   ::xml_schema::flags f,
                                   ::xml_schema::container* c)
            : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
              source_ (f, this),
              destination_ (f, this),
              link_ (f, this)
            {
              if ((f & ::xml_schema::flags::base) == 0)
              {
                ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
                this->parse (p, f);
              }
            }

            void routingTableEntryType::
            parse (::xsd::cxx::xml::dom::parser< char >& p,
                   ::xml_schema::flags f)
            {
              while (p.more_attributes ())
              {
                const ::xercesc::DOMAttr& i (p.next_attribute ());
                const ::xsd::cxx::xml::qualified_name< char > n (
                  ::xsd::cxx::xml::dom::name< char > (i));

                if (n.name () == "source" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< source_type > r (
                    source_traits::create (i, f, this));

                  this->source_.set (r);
                  continue;
                }

                if (n.name () == "destination" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< destination_type > r (
                    destination_traits::create (i, f, this));

                  this->destination_.set (r);
                  continue;
                }

                if (n.name () == "link" && n.namespace_ ().empty ())
                {
                  ::std::auto_ptr< link_type > r (
                    link_traits::create (i, f, this));

                  this->link_.set (r);
                  continue;
                }
              }

              if (!source_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "source",
                  "");
              }

              if (!destination_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "destination",
                  "");
              }

              if (!link_.present ())
              {
                throw ::xsd::cxx::tree::expected_attribute< char > (
                  "link",
                  "");
              }
            }

            routingTableEntryType* routingTableEntryType::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class routingTableEntryType (*this, f, c);
            }

            routingTableEntryType::
            ~routingTableEntryType ()
            {
            }

            // type
            //

            type::
            type (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
            : ::xml_schema::string (e, f, c)
            {
              _xsd_type_convert ();
            }

            type::
            type (const ::xercesc::DOMAttr& a,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
            : ::xml_schema::string (a, f, c)
            {
              _xsd_type_convert ();
            }

            type::
            type (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
            : ::xml_schema::string (s, e, f, c)
            {
              _xsd_type_convert ();
            }

            type* type::
            _clone (::xml_schema::flags f,
                    ::xml_schema::container* c) const
            {
              return new class type (*this, f, c);
            }

            type::value type::
            _xsd_type_convert () const
            {
              ::xsd::cxx::tree::enum_comparator< char > c (_xsd_type_literals_);
              const value* i (::std::lower_bound (
                                _xsd_type_indexes_,
                                _xsd_type_indexes_ + 2,
                                *this,
                                c));

              if (i == _xsd_type_indexes_ + 2 || _xsd_type_literals_[*i] != *this)
              {
                throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
              }

              return *i;
            }

            const char* const type::
            _xsd_type_literals_[2] =
            {
              "in",
              "out"
            };

            const type::value type::
            _xsd_type_indexes_[2] =
            {
              ::research::noc::application_mapping::unified_framework::schema::node::type::in,
              ::research::noc::application_mapping::unified_framework::schema::node::type::out
            };
          }
        }
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace node
          {
            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (const ::std::string& u,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::tree::error_handler< char > h;

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (const ::std::string& u,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (const ::std::string& u,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  u, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::sax::std_input_source isrc (is);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  const ::std::string& sid,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  const ::std::string& sid,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0,
                (f & ::xml_schema::flags::keep_dom) == 0);

              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::std::istream& is,
                  const ::std::string& sid,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
              return ::research::noc::application_mapping::unified_framework::schema::node::node (isrc, h, f, p);
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::xercesc::InputSource& i,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xsd::cxx::tree::error_handler< char > h;

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::xercesc::InputSource& i,
                  ::xml_schema::error_handler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::xercesc::InputSource& i,
                  ::xercesc::DOMErrorHandler& h,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::parse< char > (
                  i, h, p, f));

              if (!d.get ())
                throw ::xsd::cxx::tree::parsing< char > ();

              ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                ::research::noc::application_mapping::unified_framework::schema::node::node (
                  d, f | ::xml_schema::flags::own_dom, p));

              return r;
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (const ::xercesc::DOMDocument& d,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties& p)
            {
              if (f & ::xml_schema::flags::keep_dom)
              {
                ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
                  static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                  ::research::noc::application_mapping::unified_framework::schema::node::node (
                    c, f | ::xml_schema::flags::own_dom, p));

                return r;
              }

              const ::xercesc::DOMElement& e (*d.getDocumentElement ());
              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (n.name () == "node" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
              {
                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                  ::xsd::cxx::tree::traits< ::research::noc::application_mapping::unified_framework::schema::node::nodeType, char >::create (
                    e, f, 0));
                return r;
              }

              throw ::xsd::cxx::tree::unexpected_element < char > (
                n.name (),
                n.namespace_ (),
                "node",
                "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node");
            }

            ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType >
            node (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                  ::xml_schema::flags f,
                  const ::xml_schema::properties&)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
                ((f & ::xml_schema::flags::keep_dom) &&
                 !(f & ::xml_schema::flags::own_dom))
                ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
                : 0);

              ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
              const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (f & ::xml_schema::flags::keep_dom)
                doc.setUserData (::xml_schema::dom::tree_node_key,
                                 (c.get () ? &c : &d),
                                 0);

              if (n.name () == "node" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
              {
                ::std::auto_ptr< ::research::noc::application_mapping::unified_framework::schema::node::nodeType > r (
                  ::xsd::cxx::tree::traits< ::research::noc::application_mapping::unified_framework::schema::node::nodeType, char >::create (
                    e, f, 0));
                return r;
              }

              throw ::xsd::cxx::tree::unexpected_element < char > (
                n.name (),
                n.namespace_ (),
                "node",
                "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node");
            }
          }
        }
      }
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace research
{
  namespace noc
  {
    namespace application_mapping
    {
      namespace unified_framework
      {
        namespace schema
        {
          namespace node
          {
            void
            node (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));

              ::xsd::cxx::tree::error_handler< char > h;

              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
              }
            }

            void
            node (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  ::xml_schema::error_handler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xsd::cxx::xml::auto_initializer i (
                (f & ::xml_schema::flags::dont_initialize) == 0);

              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));
              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            node (::std::ostream& o,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));
              ::xsd::cxx::xml::dom::ostream_format_target t (o);
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            node (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));

              ::xsd::cxx::tree::error_handler< char > h;

              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
              }
            }

            void
            node (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  ::xml_schema::error_handler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            node (::xercesc::XMLFormatTarget& t,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::namespace_infomap& m,
                  const ::std::string& e,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::research::noc::application_mapping::unified_framework::schema::node::node (s, m, f));
              if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
              {
                throw ::xsd::cxx::tree::serialization< char > ();
              }
            }

            void
            node (::xercesc::DOMDocument& d,
                  const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  ::xml_schema::flags)
            {
              ::xercesc::DOMElement& e (*d.getDocumentElement ());
              const ::xsd::cxx::xml::qualified_name< char > n (
                ::xsd::cxx::xml::dom::name< char > (e));

              if (n.name () == "node" &&
                  n.namespace_ () == "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node")
              {
                e << s;
              }
              else
              {
                throw ::xsd::cxx::tree::unexpected_element < char > (
                  n.name (),
                  n.namespace_ (),
                  "node",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node");
              }
            }

            ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
            node (const ::research::noc::application_mapping::unified_framework::schema::node::nodeType& s,
                  const ::xml_schema::namespace_infomap& m,
                  ::xml_schema::flags f)
            {
              ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
                ::xsd::cxx::xml::dom::serialize< char > (
                  "node",
                  "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node",
                  m, f));

              ::research::noc::application_mapping::unified_framework::schema::node::node (*d, s, f);
              return d;
            }

            void
            operator<< (::xercesc::DOMElement& e, const nodeType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // cost
              //
              if (i.cost ())
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "cost",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node",
                    e));

                s << ::xml_schema::as_double(*i.cost ());
              }

              // topologyParameter
              //
              for (nodeType::topologyParameter_const_iterator
                   b (i.topologyParameter ().begin ()), n (i.topologyParameter ().end ());
                   b != n; ++b)
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "topologyParameter",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node",
                    e));

                s << *b;
              }

              // link
              //
              for (nodeType::link_const_iterator
                   b (i.link ().begin ()), n (i.link ().end ());
                   b != n; ++b)
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "link",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node",
                    e));

                s << *b;
              }

              // routingTableEntry
              //
              for (nodeType::routingTableEntry_const_iterator
                   b (i.routingTableEntry ().begin ()), n (i.routingTableEntry ().end ());
                   b != n; ++b)
              {
                ::xercesc::DOMElement& s (
                  ::xsd::cxx::xml::dom::create_element (
                    "routingTableEntry",
                    "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/node",
                    e));

                s << *b;
              }

              // id
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "id",
                    e));

                a << i.id ();
              }

              // core
              //
              if (i.core ())
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "core",
                    e));

                a << *i.core ();
              }
            }

            void
            operator<< (::xercesc::DOMElement& e, const topologyParameterType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // topology
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "topology",
                    e));

                a << i.topology ();
              }

              // type
              //
              if (i.type ())
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "type",
                    e));

                a << *i.type ();
              }

              // value
              //
              if (i.value ())
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "value",
                    e));

                a << *i.value ();
              }
            }

            void
            operator<< (::xercesc::DOMElement& e, const linkType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // type
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "type",
                    e));

                a << i.type ();
              }

              // value
              //
              if (i.value ())
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "value",
                    e));

                a << *i.value ();
              }
            }

            void
            operator<< (::xercesc::DOMElement& e, const typeType& i)
            {
              e << static_cast< const ::xml_schema::string& > (i);
            }

            void
            operator<< (::xercesc::DOMAttr& a, const typeType& i)
            {
              a << static_cast< const ::xml_schema::string& > (i);
            }

            void
            operator<< (::xml_schema::list_stream& l,
                        const typeType& i)
            {
              l << static_cast< const ::xml_schema::string& > (i);
            }

            void
            operator<< (::xercesc::DOMElement& e, const routingTableEntryType& i)
            {
              e << static_cast< const ::xml_schema::type& > (i);

              // source
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "source",
                    e));

                a << i.source ();
              }

              // destination
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "destination",
                    e));

                a << i.destination ();
              }

              // link
              //
              {
                ::xercesc::DOMAttr& a (
                  ::xsd::cxx::xml::dom::create_attribute (
                    "link",
                    e));

                a << i.link ();
              }
            }

            void
            operator<< (::xercesc::DOMElement& e, const type& i)
            {
              e << static_cast< const ::xml_schema::string& > (i);
            }

            void
            operator<< (::xercesc::DOMAttr& a, const type& i)
            {
              a << static_cast< const ::xml_schema::string& > (i);
            }

            void
            operator<< (::xml_schema::list_stream& l,
                        const type& i)
            {
              l << static_cast< const ::xml_schema::string& > (i);
            }
          }
        }
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

